- com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/user/dialog/EditUserDialog.java
I'm so sorry about this issue.
This issue occured by my last fixed issue #11.
So, I was add condition for check the null and test it.
Please review my pull request. Thank you 😄
> When only change the user's password, NullPointerException occurs in groupChange() method.

- com.cubrid.common.ui/src/com/cubrid/common/ui/compare/Messages.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/compare/Messages.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/compare/Messages_ko_KR.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/compare/schema/control/TableSchemaCompareInfoPart.java
- com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/cubrid/table/model/SchemaDDLTest.java
- com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/table/model/SchemaDDL.java
#1 
TO-DO
~1. Separate Alter DDL each other.~
2. Implement the method for auto_increment.
> Change behavior for backwards compatibility at schema compare wizard.

- com.cubrid.common.ui/src/com/cubrid/common/ui/common/control/SearchContributionComposite.java
- com.cubrid.cubridmanager.app/src/com/cubrid/cubridmanager/app/ApplicationActionBarAdvisor.java
The search button looked a bit weird and pretty crammed, so I've removed one redundant label and also made the search box and button bigger.
> Search button

- com.cubrid.common.core/src/com/cubrid/common/core/util/StringUtil.java
- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/common/control/PageSizeChoiceComposite.java
- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/editor/DatabaseDashboardEditor.java
- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/host/editor/HostDashboardEditor.java
- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/mondashboard/editor/DatabaseDashboardViewPart.java
- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/mondashboard/editor/HostDashboardViewPart.java
- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/monitoring/editor/internal/DbSystemMonitorCompositePart.java
- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/monitoring/editor/internal/HostSystemMonitorCompositePart.java
- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/service/editor/ServiceDashboardLabelProvider.java
It is desired to change from X to XB (X={K, M, G, T}) in the UI.
> Bytes: change from X to XB (X={K, M, G, T})

- com.cubrid.common.ui/src/com/cubrid/common/ui/common/preference/GeneralPreferenceComposite.java
- com.cubrid.cubridmanager.app/src/com/cubrid/cubridmanager/app/ApplicationWorkbenchWindowAdvisor.java
This function is unnecessary, so we do not use it for a while.
If this function is needed, we will activate it again.
> Disable Notice Dashboard

- com.cubrid.cubridmanager.ui/version.properties
[#69] Update version string for release the CM.
> #69 Update version string

- com.cubrid.cubridmanager.ui/version.properties
Due to a bug fix, we had to re-release and revised the version information.
> Update version string for release

- com.cubrid.common.core/src/com/cubrid/common/core/util/CompatibleUtil.java
- com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/table/task/GetAllSchemaTask.java
- com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/table/task/GetSchemaTask.java
- com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/table/task/GetUserClassIndexesTask.java
We have implemented a [Function-based index](http://www.cubrid.org/manual/en/10.1/sql/tuning.html#function-index) so that the user can use at the following list.
- Schema compare wizard
- Index information in Navigation tree
- Index tab of edit tables
> Apply function based index

- com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/dialog/AddIndexDialog.java
This PR is related with #98 .
We added [function-based index](http://www.cubrid.org/manual/en/10.1/sql/tuning.html#function-index) to make it with reverse index.
> Apply creating function-based index as reverse index

- com.cubrid.common.ui/src/com/cubrid/common/ui/query/control/SqlParser.java
Please refer to [TOOLS-4267](http://jira.cubrid.org/browse/TOOLS-4267).
> [TOOLS-4267] Aggregate function returns wrong result when used at inner function

- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/common/control/DatabaseConfigPropertyPage.java
- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/common/control/PageSizeChoiceComposite.java
Please refer to [TOOLS-4268](http://jira.cubrid.org/browse/TOOLS-4268).
> [TOOLS-4268] Configuration error in cubrid.conf due to Byte unit

- com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/common/socket/MessageUtil.java
- com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/database/task/UnloadDatabaseTask.java
Please refer to [TOOLS-4269](http://jira.cubrid.org/browse/TOOLS-4269).
> [TOOLS-4269] 'unload' do not works properly 

- com.cubrid.common.ui/src/com/cubrid/common/ui/query/editor/QueryEditorPart.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/query/editor/QueryEditorUtil.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/spi/util/LayoutUtil.java
- com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/common/model/ServerInfo.java
- com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/database/model/DatabaseInfo.java
- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/spi/util/DatabaseUtils.java
Please refet to [TOOLS-4270](http://jira.cubrid.org/browse/TOOLS-4270).
> [TOOLS-4270] Open the query editor is limited by value of MAX_NUM_APPL_SERVER and IDLE CAS

- com.cubrid.common.ui/src/com/cubrid/common/ui/query/editor/QueryEditorPart.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/query/editor/QueryEditorUtil.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/spi/util/LayoutUtil.java
- com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/common/model/ServerInfo.java
Enhancement to open the query editor by checking the CAS and opened query editor as real time.
Please refer to [TOOLS-4270](http://jira.cubrid.org/browse/TOOLS-4270).
> [TOOLS-4270] Enhancement to open the query editor.

- com.cubrid.cubridmanager.ui/version.properties
update version.properties for release/2017.08
> update version.properties for release/2017.08

- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_jp_JP.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_km_KH.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_ko_KR.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_tr_TR.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_zh_CN.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/dialog/AboutDialog.java
Please refer to [TOOLS-4276](http://jira.cubrid.org/browse/TOOLS-4276).
> [TOOLS-4276] Update information for version of client

- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_jp_JP.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_km_KH.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_ko_KR.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_tr_TR.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_zh_CN.properties
Please refer to [TOOLS-4276](http://jira.cubrid.org/browse/TOOLS-4276).
> [TOOLS-4276] Update some typos in about dialog

- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/jobauto/control/PeriodGroup.java
Please refer to [TOOLS-4272](http://jira.cubrid.org/browse/TOOLS-4272).
> [TOOLS-4272] Configuration of 'periodic back up by interval' for 'autobackupdb' fails.

- com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/control/AttributeTableViewerLabelProvider.java
Please, Refer to [TOOLS-4291](http://jira.cubrid.org/browse/TOOLS-4291)
> [TOOLS-4291] 'column comment' is shown in 'Inheritance' column at 'Table/View'

- LICENSE/License_CUBRID_Manager.txt
- com.cubrid.cubridmanager.build/build.xml
- com.cubrid.cubridmanager.build/installer/win/CUBRIDManager_with_jre.nsi
- com.cubrid.cubridmanager.build/installer/win/CUBRIDManager_x64_with_jre.nsi
Please refer to [TOOLS-4292](http://jira.cubrid.org/browse/TOOLS-4292)
> [TOOLS-4292] CUBRID Manager does not work with JAVA 9, 10.

- com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/utils/ModelUtil.java
[TOOLS-4293] Add correctTriggerValues method to correct values(actionTime, conditionTime)
Please, Refer to [TOOLS-4293](http://jira.cubrid.org/browse/TOOLS-4293)
> [TOOLS-4293] When editing the trigger already created, "SQL Script" is not shown properly

- com.cubrid.common.ui/src/com/cubrid/common/ui/spi/action/MenuProvider.java
- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/spi/action/CubridMenuProvider.java
- com.cubrid.cubridquery.ui/src/com/cubrid/cubridquery/ui/spi/action/CubridMenuProvider.java
We found a side effect and fixed it.
Please refer to [TOOLS-4295](http://jira.cubrid.org/browse/TOOLS-4295) if you want detail information. Thank you.
> [TOOLS-4295] Prevent ClassCastException

- com.cubrid.common.ui/src/com/cubrid/common/ui/spi/progress/LoadTableColumnsProgress.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/spi/progress/LoadTableRecordCountsProgress.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/spi/progress/LoadTableRecordSizeProgress.java
> [TOOLS-4290] Fixed for cast problem in JDK6 (#128)

- com.cubrid.common.ui/src/com/cubrid/common/ui/spi/persist/RecentlyUsedSQLContentPersistUtils.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/spi/persist/RecentlyUsedSQLDetailPersistUtils.java
Please refer to [TOOLS-4298](http://jira.cubrid.org/browse/TOOLS-4298).
> [TOOLS-4298] Modified to save CTE query to SQL History

- README.md
Please refer to [TOOLS-4304](http://jira.cubrid.org/browse/TOOLS-4304).
> [TOOLS-4304] Modify/Remove broken link in README

- com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/table/task/GetAllClassListTask.java
Please, Refer to [TOOLS-4308](http://jira.cubrid.org/browse/TOOLS-4308)
* [TOOLS-4308] Add a condition to WHERE clause
* [TOOLS-4308] Add ORDER BY clause
> [TOOLS-4308] [CM] Tables need to be sorted in alphabetical order in CUBRID Navigator View

- com.cubrid.common.ui/src/com/cubrid/common/ui/spi/model/MoreTablesNode.java
* Please, refer to [TOOLS-4309](http://jira.cubrid.org/browse/TOOLS-4309)
> [TOOLS-4309] [CM] Side effect of #126: system table list is attached while unfolding table view, which is unintended

- com.cubrid.common.ui/src/com/cubrid/common/ui/spi/model/MoreTablesNode.java
* Please, Refer to [TOOLS-4314](http://jira.cubrid.org/projects/TOOLS/issues/TOOLS-4314)
> [TOOLS-4314] [CM] Wrong table count is shown when a user expands the table

- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/action/CreateDatabaseAction.java
- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/control/GeneralInfoPage.java
* Please, Refer to [TOOLS-4313](http://jira.cubrid.org/projects/TOOLS/issues/TOOLS-4313)
> [TOOLS-4313] [CM] Set the default charset as ko_KR.utf8 when creating a database

- com.cubrid.common.ui/src/com/cubrid/common/ui/spi/model/MoreTablesNode.java
* Please, Refer to [TOOLS-4321](http://jira.cubrid.org/projects/TOOLS/issues/TOOLS-4321)
> [TOOLS-4321] [CM] When a user expands "More Tables" node, all table folders' table count is updated.

- com.cubrid.common.ui/plugin.properties
- com.cubrid.common.ui/plugin.xml
- com.cubrid.common.ui/plugin_jp_JP.properties
- com.cubrid.common.ui/plugin_km_KH.properties
- com.cubrid.common.ui/plugin_ko_KR.properties
- com.cubrid.common.ui/plugin_tr_TR.properties
- com.cubrid.common.ui/plugin_zh_CN.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_jp_JP.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_km_KH.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_ko_KR.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_tr_TR.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_zh_CN.properties
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/preference/GeneralPreference.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/preference/GeneralPreferenceComposite.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/preference/NavigatorPreference.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/preference/NavigatorPreferenceComposite.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/common/preference/NavigatorPreferencePage.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/spi/model/MoreTablesNode.java
- com.cubrid.common.ui/src/com/cubrid/common/ui/spi/model/loader/schema/CubridTablesFolderLoader.java
- com.cubrid.cubridmanager.app/src/com/cubrid/cubridmanager/app/CMPreferenceNodeComparator.java
* Please, Refer to [TOOLS-4319](http://jira.cubrid.org/projects/TOOLS/issues/TOOLS-4319)
> [TOOLS-4319] [CM] Change properties of unfolding 'Table' icon in 'Host Navigation' windows

- com.cubrid.common.core/src/com/cubrid/common/core/util/QueryUtil.java
* Please, Refer to [TOOLS-4322](http://jira.cubrid.org/projects/TOOLS/issues/TOOLS-4322)
> [TOOLS-4322] [CM] When a user changes a column comment in the table schema editor, the comment is not changed if a default value exists

- com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/dialog/imp/progress/ImportFromSQLRunnable.java
Please, Refer to [TOOLS-4323](http://jira.cubrid.org/browse/TOOLS-4323)
> [TOOLS-4323] [CM] An error occurs while Importing data from SQL File to Database

- com.cubrid.cubridmanager.ui/version.properties
Please, Refer to [TOOLS-4324](http://jira.cubrid.org/browse/TOOLS-4324)
> [TOOLS-4324] CUBRID Tools Release for 10.2

- com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/control/GeneralInfoPage.java
* Please, Refer to [TOOLS-4326](http://jira.cubrid.org/browse/TOOLS-4326)
> [TOOLS-4326] [CM] Database Creation Dialog is not open in CUBRID 2008 R4.0 (8.4.0.1008)

- com.cubrid.common.ui/src/com/cubrid/common/ui/query/editor/SQLContentAssistProcessor.java
- com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/CubridManagerCorePlugin.java
- com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/common/jdbc/JDBCConnectionManager.java
* Please, Refer to [TOOLS-4325](http://jira.cubrid.org/browse/TOOLS-4325)
> [TOOLS-4325] [CM] When a user uses SQL Code Autocompletion function, CM flag needs to be appended to Connection string

- com.cubrid.cubridmanager.ui/version.properties
Update to version 10.2.0.0001 -> 10.2.0.0002
> CUBRID Admin 10.2.0.0002
