CUBRID/cubrid-manager

com.cubrid.common.ui/src/com/cubrid/common/ui/common/preference/JdbcManageComposite.java, com.cubrid.common.ui/src/com/cubrid/common/ui/spi/TableViewerSorter.java
This fix solves the issue with the JDBC driver ordering in the Preferences/JDBC Management tab. At first, they were ordered alphabetically and that was not desired, so I have ordered them based on the version number.
TableViewerSorter.java now contains a hashmap that can have an arbitrary comparator for each table column (the key of this hashmap is the column value). When sorting a column, I check whether the hashmap contains a comparator for that column or not and, if it exists, use it.
=> Sort jdbc drivers

com.cubrid.common.ui/src/com/cubrid/common/ui/query/editor/QueryEditorPart.java
Very small improvement: when closing the last sql editor, the counter would just increment. Now, if it's the last one and you close it, the counter just gets reset to 1.
=> CloseQueryEditor: if all tabs are closed, start sqlEditorCounter at 1

com.cubrid.common.ui/src/com/cubrid/common/ui/query/control/QueryExecuter.java
I have deleted unnecessary logic and comments in `QueryExecuter#makeTable()`.
Deleted logic is related with printing elapsed time after query was executed.
Before fixed that logic, elapsed time was printed as twice.
After I fixed that, elapsed time is print as once.
=> Fixed that elapsed time was printed as twice

com.cubrid.common.ui/src/com/cubrid/common/ui/er/editor/ERSchemaToolBar.java
This commit fixes the "Auto layout" button's height so that its text is shown fully. This button is found in Pro Tools->ERD Editor
=> Auto layout button

com.cubrid.common.ui/plugin.xml, com.cubrid.cubridmanager.app/plugin.xml, com.cubrid.cubridmanager.ui/plugin.xml
The search box in the preferences widget was using only the names of the tabs as keywords. I have added useful search keywords for every individual tab, making the search box more useful.
=> FixSearch: add useful keywords to search in preferences

com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/dialog/PstmtSQLDialog.java
The execute defined sql text box is too small for its function.
By making the widget bigger and by giving the sql text box part a 50% area, the sql text box now looks ok.
=> ExecuteSQLWindow: fix the query text box

com.cubrid.common.core/src/com/cubrid/common/core/util/QueryUtil.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/Messages.properties, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/dialog/exp/ExportConfigManager.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/dialog/exp/ExportSettingForLoadDBPage.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/dialog/exp/ExportSettingPage.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/AbsExportDataHandler.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/ExportLoadDBHandler.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/ExportToTxtHandler.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/ExportToXlsHandler.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/ExportToXlsxHandler.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/ExprotToOBSHandler.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/ExprotToSqlHandler.java
This PR is related with #17.
Before I changed codes, Export function was very slow at database which have many tables and columns.
The reasons as below.
- All tables and columns were selected from database at the same time when "next" button was fired in "Choose the exporting type" page. But columns information is unnecessary in this page.
- When users clicked checkbox about "Select All" in "Configure the exporting options" then all columns were checked in for-loop. This is unnecessary too.
So, I refined about Export function like below.
- Deleted codes which is select all columns when "next" button was fired in "Choose the exporting type" page.
- Above logic is moved to "Confirm the exporting options" page and execute belong to only checked tables when "Finish" button was fired.
- …
=> Enhancement for Export function

com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages.properties, com.cubrid.common.ui/src/com/cubrid/common/ui/common/preference/ShowDashboardDialog.java
The message is too big for this unresizable window. Adding a \n splits this message and it looks ok now.
=> ShowDashboard: add \n to message so it splits

com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/ResultSetDataCache.java, com.cubrid.common.ui/src/com/cubrid/common/ui/query/control/QueryExecuter.java, com.cubrid.common.ui/src/com/cubrid/common/ui/query/editor/QueryEditorPart.java
When users execute the query in CM then works to release the result objects - columns, datas, etc - using `dispose()` in `QueryEditorPart#runQuery()` for releasing resources.
Before I changed this codes, `dispose()` released caching data too.
But if caching data contains LOB types with `null` data cause `NullPointerException` and CM was hanged.
As above reason, when I was ran below query in CM at first time, result was returned.
However, next ran same query didn't return the result and hanged because caching data contains LOB tpyes with `null` data.
So, I add the inspecting logic about `NullPointerException` and separate `dispose()` method to `dispose()` and `initBeforeRunQuery()`.
```sql
CREATE TABLE clob_test (code1 VARCHAR(10), code2 INT, code3 clob) ;
INSERT INTO clob_test VALUE …
```
=> When running query which contains null data in LOB types, CM was hanged.

com.cubrid.common.core/src/com/cubrid/common/core/util/QueryUtil.java, com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/table/task/GetUserClassColumnsTask.java
This PR is related with #15.
CUBRID version in 9.2.0 to 9.2.6, non pk column shown as pk column in host navigation tree.
That is engine's bug and I resolved it in CM.
Please check my PR.
Thank you.
=> Wrong pk icon in the navigation tree

com.cubrid.common.core/src/com/cubrid/common/core/util/QueryUtil.java, com.cubrid.common.core/src/com/cubrid/common/core/util/StringUtil.java, com.cubrid.common.ui/src/com/cubrid/common/ui/query/control/QueryExecuter.java
When users used `Selected rows> Copy INSERT to Clipboard` and `Selected rows> Copy UPDATE to Clipboard` didn't escaped single and double quotation.
So, copied Insert and Update sentence occured syntax error when string data contains single or double quotation.
After I changed this, that function good working when string data contains single and double quotations.
And there was one bug when using `Selected rows> Copy UPDATE to Clipboard` if target table haven't primary key.
I have fixed that too.
=> Escaping quotation when executing COPYnPASTE operation on Insert and Update statement

com.cubrid.common.ui/src/com/cubrid/common/ui/query/control/QueryExecuter.java
When selecting clob with empty string cause `ArrayIndexOutOfBounds` Exception in `QueryExecuter#loadClobData` because reading data from that clob returns -1.
=> Query result shows nothing when selecting clob contains empty string.

com.cubrid.common.core/src/com/cubrid/common/core/util/StringUtil.java, com.cubrid.common.ui/src/com/cubrid/common/ui/query/control/QueryExecuter.java
This PR is related with #56.
You can see the fixed list as below.
- When `NULL` value was contained in the selected row, value clause returned not `NULL` but `NULN`.
- If single or double quotations exist in the start and end position, before code was not escaping that.
- Below image is result of select.
-  Before I fixed this, copied result was look like below.
```sql
INSERT INTO quote (col1, col2) VALUES (1, 'abc');
INSERT INTO quote (col1, col2) VALUES (2, 'defg');
```
- After I fixed, copied result was look like below.
```sql
INSERT INTO quote (col1, col2) VALUES (1, '''abc''');
INSERT INTO quote (col1, col2) VALUES (2, '"defg"');
```
Please check my PR. Thank you.
=> Fix typo and additional escaping quotes in "selected row > copy Insert & Update"

com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/common/control/PageSizeChoiceComposite.java
When I changed `data_buffer_size` to 1G and I have confirmed on CM, that parameter's unit size shows invalid unit to me.
- Checking `data_buffer_size`'s value in CSQL
- Invalid unit displayed in CM (not GB but MB)
So, I fixed that in `PageSizeChoiceComposite#setUnitOfSize`.
Please check my PR.
Thank you. 😄
=> Fixed invalid unit in Server Parameter

com.cubrid.common.core/src/com/cubrid/common/core/schemacomment/SchemaCommentHandler.java, com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/table/task/UpdateDescriptionTask.java
CM's comments function couldn't found name of tables and columns when user inserted data to the `_cub_schema_comments` as manually using upper case.
1. Install the comments function
2. Creating test table
```sql
CREATE TABLE test (col1 INT, col2 DATETIME);
```
3. Insert data to the `_cub_schema_comments` as manually using upper case
```sql
INSERT INTO _cub_schema_comments VALUES('TEST', 'COL1', 'this is description', SYSDATETIME, CURRENT_USER);
```
4. Open the `edit table...` and see the opened window.
You can't see any comments - Table memo and Column memo - like below image. 
So, I changed `SELECT` and `UPDATE` queries using `LOWER()` and `toLowerCase()`.
Please check my PR. Thank  you. :smile:
=> Table and Column's upper case issue in _cub_schema_comments

com.cubrid.common.ui/src/com/cubrid/common/ui/common/control/BrokerConfigEditComposite.java
When users change the broker's configuration in CM but that was not working.
1. Connect host
2. Right click the host -> Configure Parameter -> Edit Broker Config
3. Click the save button
`validate()` method returned error dialog when broker's name is not blank. 
~~So, I just added the exclamation mark to the front of `isNotBlank()` in the `validate()`.~~
So, I just changed the method from `isNotBlank()` to `isBlank()` in the `validate()`.
Please check my PR. Thank you. :smile:
=> Fix the error of Edit Broker Config

com.cubrid.common.core/src/com/cubrid/common/core/util/CubridUtil.java, com.cubrid.common.ui/src/com/cubrid/common/ui/query/control/QueryExecuter.java
When I executed about `SHOW` statement in CM that result was displayed in not `Table` but `StyledText`.
That result in the above image is hard to understand what means about values because there is no names or informations about columns.
But you can display that result on the `Table` without changing codes just adding `--` above your sql. It looks like a bug!
I found problem in constructor of `QueryExecutor` when   checking sql is command or not using `isCommand = CubridUtil.isCommand(orignQuery);`.
In `isCommand()`, `SHOW` statement is processed as command like below.
```java
String[] wordArray = sql.split("\\s|\\r|\\n|\\t");
if (wordArray.length > 0) {
if ("SHOW".equalsIgnoreCase(wordArray[0]) || "SET".equalsIgnoreCase(wordArray[0]))
return true;
}
```
I think this is not good to users …
=> display the output of 'SHOW' command in Table format

com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/cubrid/sp/model/SPArgsInfoTest.java, com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/cubrid/sp/model/SPInfoTest.java, com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/cubrid/sp/model/SpModelTest.java
I didn't fixed some test cases for calling SPArgsInfo's `constructor` when I implemented SP's comment before.
So I fixed that in this PR. 
Please check my PR. Thank you. 😄
=> Fix testcases's error about comment of SP

com.cubrid.common.core/src/com/cubrid/common/core/util/QueryUtil.java
When users executed the `Export` feature in CM, the order of exported data was ordered in alphabetical.
So, the order of table's column and data was not matched and not working when users executed `Import` feature using exported data file.
Because above reason, `getSelectSQL()` was fixed.
Please check my PR. Thank you.
=> Fix columns order as correctly when data is exported.

com.cubrid.common.core/src/com/cubrid/common/core/util/StringUtil.java, com.cubrid.common.ui/src/com/cubrid/common/ui/spi/util/paramSetter/BitParamSetter.java
When users used `BIT` or `BIT VARYING` types in feature of `Import` they received error about `java.lang.ClassCastException` in [CM](https://github.com/CUBRID/cubrid-manager).
That's reason is `BIT` or `BIT VARYING` were parsed as `String` then casted to `byte[]`.
- In [csql](http://cubrid.org/manual/en/10.0/csql.html), `BIT` or `BIT VARYING` data shown as `String` like below. (The third column: `attach`)
- [CM](https://github.com/CUBRID/cubrid-manager) parse `BIT` or `BIT VARYING` as `String` like above data but there is no checking logic for `String` as below.
- Codes of [CM](https://github.com/CUBRID/cubrid-manager): `BitParamSetter#handle()`
```java
if (value instanceof Blob) {
Blob blob = (Blob) value;
InputStream in = blob.getBinaryStream();
bytesvalues = getBytesFromInputSteam(in); …
```
=> Fix binding error when using type of bit in import feature

com.cubrid.common.core/src/com/cubrid/common/core/util/CompatibleUtil.java
When users connect with CUBRID 10.1 then CM pop up the below message dialog.
So, we fixed this for release the [CUBRID](https://github.com/CUBRID/cubrid) version of 10.1
=> Fix invalid error popup when connect the version of 10.1

com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/AbsExportDataHandler.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/ExportLoadDBHandler.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/ExportToTxtHandler.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/ExportToXlsHandler.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/ExportToXlsxHandler.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/ExprotToOBSHandler.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/export/handler/ExprotToSqlHandler.java
This issue is related with PR of #43.
```java
if (exportConfig.getSQL(name) != null) {
sql = exportConfig.getSQL(name);
}
```
The above code will generate the SQL to be used in the export.
However, the above code was deleted from # 43 PR, and SQL could not be created normally, resulting in a syntax error.
So, We fixed that issue this PR.
=> Fix the bug about export all the results to a file

com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/dialog/CreateViewDialog.java
SQL Script of View don't have any scroll functions either vertical nor horizontal.
For this reason, it was uncomfortable to see long definition up to now.
Now, we added vertical/horizontal scroll function in it.
=> Make scrollable in the SQL Script of View 

com.cubrid.common.ui/src/com/cubrid/common/ui/query/control/DatabaseNavigatorMenu.java, com.cubrid.common.ui/src/com/cubrid/common/ui/query/preference/QueryPropertyComposite.java
The setting of auto-commit could enable or disable in the preferences.
But this feature was not working when user open the new query editor because Auto commit was set the true always.
This is intended function at [TOOLS-1250](http://jira.cubrid.org/browse/TOOLS-1250). (Unfortunately you can't see the information if you don't have authority of jira)
But this is not known to common users and they would be confused by this.
To summarize the [TOOLS-1250](http://jira.cubrid.org/browse/TOOLS-1250), setting auto-commit to off and performing a query can result in a lock, which can cause the database to hang and cause a failure.
So, this feature is removed in Preferences.
=> Delete the auto commit setting in Preferences

com.cubrid.common.core/src/com/cubrid/common/core/util/StringUtil.java, com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/table/dialog/imp/progress/AbsImportRunnable.java
If there is a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) in UTF-8 files, the import feature will not output the first data correctly.
- Data example (csv format)
```
1234567890
2345678901
3456789012
4567890123
5678901234
```
- Result
So, when using UTF-8 files, we added code to remove the [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) if there is.
=> BOM processing in the import feature

com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/table/task/GetSchemaTask.java
If the `_cub_schema_comments` table does not exist, right-clicking on the table list resulted the `NullPointerException`.
So we fixed this.
=> Corrected the NullPointerException when right-clicking a table list

com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/common/model/ServerVersion.java
Displaying engine's version information is not same at each engines.
```
CUBRID 2008 R4.4 (8.4.4.17007) (64bit release build for linux_gnu) (Dec 26 2016 14:54:31)
CUBRID 9.3 (9.3.6.0002) (64bit release build for linux_gnu) (Feb 29 2016 19:36:35)
```
Because of above reason, separating version string using  `StringTokenizer` makes error when using engine of 8.x version.
So, we changed that to Regular Expression.
Please check my PR.
Thank you. 😄
=> Can't connect the CM when using 8.x engine

com.cubrid.common.ui/src/com/cubrid/common/ui/query/editor/QueryEditorUtil.java
Added logic to ensure that query editor is open and running.
Please refer to [TOOLS-4270](http://jira.cubrid.org/browse/TOOLS-4270).
=> [TOOLS-4270] Added logic to ensure that query editor is open and running.

com.cubrid.cubridmanager.build/installer/win/CUBRIDManager.nsi, com.cubrid.cubridmanager.build/installer/win/CUBRIDManager_with_jre.nsi, com.cubrid.cubridmanager.build/installer/win/CUBRIDManager_x64.nsi, com.cubrid.cubridmanager.build/installer/win/CUBRIDManager_x64_with_jre.nsi
Please refer to [TOOLS-4274](http://jira.cubrid.org/browse/TOOLS-4274).
=> [TOOLS-4274] CUBRID Manager version during setup is incorrect

com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/dialog/DeleteDatabaseConfirmDialog.java
[TOOLS-4280] Change the width of 'DBA Confirm Dialog' to key-in a password easily
=> [TOOLS-4280] Window for typing PASSWORD is too small and hard to key-in a password in DATABASE delete menu

com.cubrid.common.ui/src/com/cubrid/common/ui/spi/progress/LoadTableColumnsProgress.java, com.cubrid.common.ui/src/com/cubrid/common/ui/spi/progress/LoadTableRecordCountsProgress.java, com.cubrid.common.ui/src/com/cubrid/common/ui/spi/progress/LoadTableRecordSizeProgress.java
In JDK version 6, the build fails because the Object is not cast to primitive type by force.
So we changed the casting of the primitive type like int, boolean.
Example of casting failure in JDK 6.
```Java
public class Test {
public static void main(String[] args) {
Object io = 10;
int i = (int) io;
}
}
```
```
[hun-a@localhost ~]$ javac -version
javac 1.6.0_45
[hun-a@localhost ~]$ javac Test.java
Test.java:4: inconvertible types
found   : java.lang.Object
required: int
int i = (int) io;
^
1 error
```
=> [TOOLS-4290] Fixed for cast problem in JDK6

com.cubrid.common.core/src/com/cubrid/common/core/schemacomment/SchemaCommentHandler.java
Please, Refer to [TOOLS-4307](http://jira.cubrid.org/browse/TOOLS-4307)
* [TOOLS-4307] Change not to use QuerySyntax.escapeKeyword method
=> [CM] 'TABLE Comment is not properly shown in 'Edit Table...' sub-menu when a table name belong to CUBRID Keywords.

com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/table/task/GetAllClassListTask.java
* Please, Refer to [TOOLS-4317](http://jira.cubrid.org/browse/TOOLS-4317)
=> [TOOLS-4317] [CM] If 'oracle_style_empty_string=yes' is added in cubrid.conf, Tables are not shown in the CM Navigator View

com.cubrid.cubridmanager.build/installer/win/CUBRIDManager.nsi, com.cubrid.cubridmanager.build/installer/win/CUBRIDManager_with_jre.nsi, com.cubrid.cubridmanager.build/installer/win/CUBRIDManager_x64.nsi, com.cubrid.cubridmanager.build/installer/win/CUBRIDManager_x64_with_jre.nsi
* Please, Refer to [TOOLS-4329](http://jira.cubrid.org/browse/TOOLS-4329)
=> [TOOLS-4329] [CM] Version string is incorrect on CUBRID Manager Installation

com.cubrid.common.core/src/com/cubrid/common/core/util/CompatibleUtil.java
* Please, Refer to [TOOLS-4332](http://jira.cubrid.org/browse/TOOLS-4332)
=> [TOOLS-4332] [CUBRID Admin] Warning pop-up shows up even if an user uses right version of driver (10.2.1)
